---
- hosts: [all]
  sudo: yes

  tasks:
    - name: test connection
      ping:
      remote_user: ubuntu

    # update repository
    - name: Replace apt repository src file
      template: src=templates/sources.list dest=/etc/apt/sources.list

    - name: update index file
      apt: update_cache=yes force=yes

    - name: Install Tomcat7
      action: apt pkg=tomcat7 state=installed update_cache=yes force=yes
      tags: common

    ##
    # Deploy web-application
    - name: Deploy application archive 
      copy: src=/home/out/case-1/expenses.war dest=/var/lib/tomcat7/webapps

    - name: Restart Tomcat 7
      action: service name=tomcat7 state=restarted
