---
- hosts: [all]
  sudo: yes

  vars:
    mysql_password: p4ssw0rd
    app_mysql_user: hpsa
    app_mysql_password: demo
    dump_path: ./database/dump.sql
    app_db_name: hpsa_demo

  tasks:
    - name: test connection
      ping:
      remote_user: ubuntu

    # update repository
    - name: Replace apt repository src file
      template: src=templates/sources.list dest=/etc/apt/sources.list

    - name: update index file
      apt: update_cache=yes force=yes

    ##
    # Apt package installation of required software.
    #
    - name: Insall MySQL
      action: apt pkg={{ item }} state=installed update_cache=yes force=yes
      with_items:
        - mysql-server
        - mysql-client
        - unzip
        - python-mysqldb

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file, my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2.yaml dest=/etc/mysql/my.cnf    

    ##
    # Restart services
    #
    - name: Restart MySQL
      action: service name=mysql state=restarted

    ##
    # MySQL Authentication
    #
    - name: MySQL | Authentication      
      mysql_user: name=root host={{ item }} password={{ mysql_password }} state=present update_password=always
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1
        - localhost      
      mysql_user:
        name={{ app_mysql_user }}
        host=%
        priv=*.*:ALL,GRANT state=present
        password={{ app_mysql_password }}

    - name: Create DB
      mysql_db: 
        name={{ app_db_name }}
        login_user={{ app_mysql_user }}
        login_password={{ app_mysql_password }}
        state=present

     - name: Copy Dump file
       copy: src={{dump_path}} dest=/tmp

    - name: Setup from Dump
      mysql_db: 
        name={{ app_db_name }}
        login_user={{ app_mysql_user }}
        login_password={{ app_mysql_password }}
        target=/tmp/dump.sql
        state=import