- name: Restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to run 
  local_action: wait_for host={{inventory_hostname}} state=started
  sudo: false

- name: Start slave 
  command: service mysql start
