 - name: Add java repository
   apt_repository: repo='ppa:webupd8team/java' update_cache=yes state=present
 - name: License accepting
   shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
