---
- hosts: case-1-db
  remote_user: ubuntu
  sudo: yes

  vars:
    mysql_password: p4ssw0rd
    app_mysql_user: hpsa
    app_mysql_password: demo
    app_path: /home/hpsa-demo/hpsa-demo-case2/source/demo-case2/
    dump_path: /home/hpsa-demo/hpsa-demo-case2/db/dump.sql    
    app_root: /home/hpsa-demo/
    app_db_name: hpsa_demo

  tasks:
    - name: test connection
      ping:
      remote_user: ubuntu

    ##
    # Apt package installation of required software.
    #
    - name: Insall MySQL and Git
      action: apt pkg={{ item }} state=installed update_cache=yes
      with_items:
        - mysql-server
        - mysql-client
        - unzip
        - python-mysqldb
        - git-core

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file, my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2.yaml dest=/etc/mysql/my.cnf    

    ##
    # Restart services
    #
    - name: Restart MySQL
      action: service name=mysql state=restarted

    ##
    # MySQL Authentication
    #
    - name: MySQL | Authentication      
      mysql_user: name=root host={{ item }} password={{ mysql_password }} state=present update_password=always
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1
        - localhost      
      mysql_user:
        name={{ app_mysql_user }}
        host=%
        priv=*.*:ALL,GRANT state=present
        password={{ app_mysql_password }}

    ##
    # Clone sources from git
    - name: Get Case sources from GIT
      git: 
        repo=https://hpsa:!Microsoft1@bitbucket.org/hpsa/hpdemo.git
        dest={{ app_root }}

    - name: Create DB
      mysql_db: 
        name={{ app_db_name }}
        login_user={{ app_mysql_user }}
        login_password={{ app_mysql_password }}
        state=present
    - name: Setup from Dump
      mysql_db: 
        name={{ app_db_name }}
        login_user={{ app_mysql_user }}
        login_password={{ app_mysql_password }}
        target={{ dump_path }}
        state=import